# Generated by Django 6.0.7 on 2026-07-22 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.SlugField(max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon_key', models.CharField(choices=[('racket', 'Racket'), ('ball-orange', 'Ball (orange)'), ('ball-teal', 'Ball (teal)'), ('ball-dark', 'Ball (dark)'), ('ball-amber', 'Ball (amber)'), ('paddle', 'Paddle'), ('rope', 'Rope'), ('frisbee', 'Frisbee')], max_length=20)),
                ('listed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('mon-thu', 'Monday & Thursday'), ('tue-wed-fri', 'Tuesday, Wednesday & Friday')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='equipment.equipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
